<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <!--<TargetFrameworks Condition="$([MSBuild]::IsOsPlatform('Windows'))">$(TargetFrameworks);net481</TargetFrameworks>-->
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <LangVersion>latest</LangVersion>    
  </PropertyGroup>
  
  <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>bin\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".gitignore" />
  </ItemGroup>
  <!--
  <ItemGroup Condition=" '$(TargetFramework)' == 'net481' ">
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>
  -->
  <!--
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
  </ItemGroup>
  -->
  
  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" Version="10.0.11" />
  </ItemGroup>

</Project>
