name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore "m3u8.github-special.sln"
    - name: Build
      run: dotnet build "m3u8.github-special.sln" --no-restore
    - name: Test
      run: dotnet test "m3u8.github-special.sln" --no-build --verbosity normal
